'use client';

import { Sparkles, Send } from 'lucide-react';

// AI Copilot conversation describing the real Incident Post-Mortem Generator workflow
const conversation = [
  {
    role: 'user' as const,
    text: 'Build a workflow that runs after a PagerDuty incident resolves. It should fetch the incident timeline and error logs in parallel, use Claude to write a structured post-mortem, then extract action items and create Jira tickets while also sharing the post-mortem on Slack.',
  },
  {
    role: 'assistant' as const,
    text: null,
    workflow: {
      name: 'Incident Post-Mortem Generator',
      nodes: [
        { icon: '⚡', label: 'Incident Resolved', detail: 'PagerDuty Webhook' },
        { icon: '📟', label: 'PagerDuty Timeline', detail: 'Get incident timeline' },
        { icon: '📊', label: 'Fetch Error Logs', detail: 'Datadog log search' },
        { icon: '🤖', label: 'Generate Post-Mortem', detail: 'Claude 3.5 Sonnet' },
        { icon: '📝', label: 'Extract Action Items', detail: 'GPT-4o-mini' },
        { icon: '🎫', label: 'Create Jira Tickets', detail: 'SRE project' },
        { icon: '💬', label: 'Share Post-Mortem', detail: 'Slack #incidents' },
        { icon: '✅', label: 'Complete', detail: 'Workflow done' },
      ],
      summary: 'I created an 8-node pipeline with two parallel fan-outs. The trigger fetches PagerDuty timeline and error logs in parallel, merges them into Claude 3.5 Sonnet for a structured post-mortem (summary, impact, timeline, root cause, action items), then fans out again to extract action items as Jira tickets and share the post-mortem on Slack.',
    },
  },
  {
    role: 'user' as const,
    text: 'Add a severity check after the post-mortem. If it is a SEV-1, also page the VP of Engineering on Slack and create an executive summary with GPT-4.',
  },
  {
    role: 'assistant' as const,
    text: 'Done. I added a condition node after the post-mortem that checks the severity field. SEV-1 incidents now trigger two additional steps in parallel: a Slack DM to the VP of Engineering with an executive summary generated by GPT-4, and an escalation tag on the Jira tickets. SEV-2 and below follow the original flow. The canvas has been updated.',
    workflow: null,
  },
];

export function MockupAICopilot() {
  return (
    <div className="overflow-hidden rounded-xl border border-gray-200 dark:border-mono-border shadow-2xl bg-white dark:bg-[#1e1e1e]">
      {/* Top bar */}
      <div className="flex items-center justify-between border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-[#252525] px-4 py-2.5">
        <div className="flex items-center gap-3">
          <div className="flex gap-1.5">
            <span className="h-3 w-3 rounded-full bg-red-400" />
            <span className="h-3 w-3 rounded-full bg-yellow-400" />
            <span className="h-3 w-3 rounded-full bg-green-400" />
          </div>
          <div className="h-4 w-px bg-gray-200 dark:bg-gray-600" />
          <div className="flex items-center gap-1">
            <span className="text-[10px] px-2 py-1 rounded text-gray-400 dark:text-gray-500 font-medium">Canvas</span>
            <span className="text-[10px] px-2 py-1 rounded text-gray-400 dark:text-gray-500 font-medium">Code</span>
            <span className="text-[10px] px-2 py-1 rounded bg-brand-100 dark:bg-brand-500/20 text-brand-700 dark:text-brand-300 font-medium flex items-center gap-1">
              <Sparkles className="h-3 w-3" /> AI Copilot
            </span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-[9px] px-1.5 py-0.5 rounded bg-brand-100 dark:bg-brand-500/15 text-brand-600 dark:text-brand-400 font-medium">GPT-4o</span>
        </div>
      </div>

      {/* Chat area */}
      <div className="p-4 space-y-4" style={{ minHeight: 380 }}>
        {conversation.map((msg, i) => (
          <div key={i} className="flex gap-3">
            {/* Avatar */}
            <div className={`flex-shrink-0 h-6 w-6 rounded-full flex items-center justify-center text-[10px] font-bold ${
              msg.role === 'user'
                ? 'bg-gray-200 dark:bg-gray-700 text-gray-600 dark:text-gray-300'
                : 'bg-brand-100 dark:bg-brand-500/20 text-brand-600 dark:text-brand-400'
            }`}>
              {msg.role === 'user' ? 'S' : <Sparkles className="h-3 w-3" />}
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0">
              {msg.text && (
                <p className={`text-xs leading-relaxed ${
                  msg.role === 'user'
                    ? 'text-gray-800 dark:text-gray-200'
                    : 'text-gray-600 dark:text-gray-300'
                }`}>
                  {msg.text}
                </p>
              )}

              {/* Workflow preview card */}
              {msg.role === 'assistant' && msg.workflow && (
                <div className="mt-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-[#252525] overflow-hidden">
                  <div className="px-3 py-2 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-semibold text-gray-700 dark:text-gray-300">{msg.workflow.name}</span>
                      <span className="text-[9px] px-1.5 py-0.5 rounded bg-green-100 dark:bg-green-500/15 text-green-700 dark:text-green-400 font-medium">Generated</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <button className="text-[9px] px-2 py-0.5 rounded border border-gray-200 dark:border-gray-600 text-gray-500 dark:text-gray-400 font-medium hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">Edit in Canvas</button>
                      <button className="text-[9px] px-2 py-0.5 rounded bg-brand-500 text-white font-medium">Apply</button>
                    </div>
                  </div>

                  {/* Node flow preview */}
                  <div className="px-3 py-2.5 flex flex-wrap gap-1.5">
                    {msg.workflow.nodes.map((node, ni) => (
                      <div key={ni} className="flex items-center gap-1">
                        <div className="flex items-center gap-1.5 rounded-md border border-gray-200 dark:border-gray-600 bg-white dark:bg-[#2a2a2a] px-2 py-1">
                          <span className="text-[10px]">{node.icon}</span>
                          <div>
                            <div className="text-[9px] font-medium text-gray-700 dark:text-gray-300">{node.label}</div>
                            <div className="text-[8px] text-gray-400 dark:text-gray-500">{node.detail}</div>
                          </div>
                        </div>
                        {ni < msg.workflow.nodes.length - 1 && (
                          <span className="text-gray-300 dark:text-gray-600 text-xs">&rarr;</span>
                        )}
                      </div>
                    ))}
                  </div>

                  <div className="px-3 py-2 border-t border-gray-200 dark:border-gray-700">
                    <p className="text-[10px] text-gray-500 dark:text-gray-400 leading-relaxed">{msg.workflow.summary}</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Input area */}
      <div className="border-t border-gray-200 dark:border-gray-700 px-4 py-3 bg-gray-50 dark:bg-[#252525]">
        <div className="flex items-center gap-2">
          <div className="flex-1 flex items-center gap-2 rounded-lg border border-gray-200 dark:border-gray-600 bg-white dark:bg-[#2a2a2a] px-3 py-2">
            <Sparkles className="h-3.5 w-3.5 text-brand-400 flex-shrink-0" />
            <span className="text-[11px] text-gray-400 dark:text-gray-500">Describe what you want to build or modify...</span>
          </div>
          <button className="flex-shrink-0 h-8 w-8 rounded-lg bg-brand-500 flex items-center justify-center text-white hover:bg-brand-600 transition-colors">
            <Send className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
    </div>
  );
}
